services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "a26873@svalero.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "5050:80"

  api:
    image: albertorodriguezpenalva/back-aws:latest
    build:
      context: ./Backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "6873:6873"
    environment:
      - ConnectionStrings__DefaultConnection=Host=mypostgredb.cfp4unu0zy6e.us-east-1.rds.amazonaws.com;Port=5432;Database=postgres;Username=postgres;Password=Ab11072004.

  front:
    image: albertorodriguezpenalva/front-aws:latest
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - api