// <auto-generated />
using System;
using AA2_CS.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace aa2_alberto_rodriguez_penalva.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260428104215_AddAchievementsBodyMetricsExercises")]
    partial class AddAchievementsBodyMetricsExercises
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AA2_CS.Model.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequirementType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequirementValue")
                        .HasColumnType("integer");

                    b.Property<int>("RewardGold")
                        .HasColumnType("integer");

                    b.Property<string>("RewardItemId")
                        .HasColumnType("text");

                    b.Property<int>("RewardXP")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("achievements", (string)null);
                });

            modelBuilder.Entity("AA2_CS.Model.BodyMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float?>("Arms")
                        .HasColumnType("real");

                    b.Property<float?>("BodyFat")
                        .HasColumnType("real");

                    b.Property<float?>("Chest")
                        .HasColumnType("real");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("ProgressPhotoUrl")
                        .HasColumnType("text");

                    b.Property<float?>("Thighs")
                        .HasColumnType("real");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<float?>("Waist")
                        .HasColumnType("real");

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("bodymetrics", (string)null);
                });

            modelBuilder.Entity("AA2_CS.Model.EmailVerification", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("expiresat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isused")
                        .HasColumnType("boolean");

                    b.Property<int>("userid")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("emailverifications", (string)null);
                });

            modelBuilder.Entity("AA2_CS.Model.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommonMistakes")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Instructions")
                        .HasColumnType("text");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("exercises", (string)null);
                });

            modelBuilder.Entity("AA2_CS.Model.Item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("bonus")
                        .HasColumnType("integer");

                    b.Property<string>("imageUrl")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("price")
                        .HasColumnType("integer");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("AA2_CS.Model.NotificationPreference", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("inactivityDays")
                        .HasColumnType("integer");

                    b.Property<bool>("inactivityEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("purchasesEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("roomsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("subscriptionExpiryEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("updatedat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("userid")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("userid")
                        .IsUnique();

                    b.ToTable("notificationpreferences", (string)null);
                });

            modelBuilder.Entity("AA2_CS.Model.Plan", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("userid")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("AA2_CS.Model.Purchase", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("itemid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("purchasedate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("userid")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("itemid");

                    b.HasIndex("userid");

                    b.ToTable("purchases", (string)null);
                });

            modelBuilder.Entity("AA2_CS.Model.Room", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("localization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("minconsistency")
                        .HasColumnType("integer");

                    b.Property<int>("minlevel")
                        .HasColumnType("integer");

                    b.Property<int>("minstats")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("AA2_CS.Model.Subscription", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("endDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enddate");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<decimal>("monthlyPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("monthlyPrice");

                    b.Property<string>("planType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("planType");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("startdate");

                    b.Property<int>("userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("id");

                    b.HasIndex("userid");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("AA2_CS.Model.Task", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("difficulty")
                        .HasColumnType("integer");

                    b.Property<bool>("iscompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("reward")
                        .HasColumnType("integer");

                    b.Property<string>("trainingfocus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("AA2_CS.Model.TaskExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("RestSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("Sets")
                        .HasColumnType("integer");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TaskId");

                    b.ToTable("taskexercises", (string)null);
                });

            modelBuilder.Entity("AA2_CS.Model.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("avatarUrl")
                        .HasColumnType("text");

                    b.Property<int>("consistencystreak")
                        .HasColumnType("integer");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("endurance")
                        .HasColumnType("integer");

                    b.Property<int?>("equippedEnduranceId")
                        .HasColumnType("integer");

                    b.Property<int?>("equippedStrengthId")
                        .HasColumnType("integer");

                    b.Property<int>("experience")
                        .HasColumnType("integer");

                    b.Property<int>("gold")
                        .HasColumnType("integer");

                    b.Property<bool>("isEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<int>("level")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("passwordhash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("strength")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("equippedEnduranceId");

                    b.HasIndex("equippedStrengthId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AA2_CS.Model.UserAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AchievementId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsNew")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserId");

                    b.ToTable("userachievements", (string)null);
                });

            modelBuilder.Entity("AA2_CS.Model.UserDTO", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("consistencystreak")
                        .HasColumnType("integer");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("endurance")
                        .HasColumnType("integer");

                    b.Property<int>("gold")
                        .HasColumnType("integer");

                    b.Property<int>("level")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("passwordhash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("strength")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("UserDTOs");
                });

            modelBuilder.Entity("AA2_CS.Model.UserRoom", b =>
                {
                    b.Property<int>("userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<int>("roomid")
                        .HasColumnType("integer")
                        .HasColumnName("roomid");

                    b.HasKey("userid", "roomid");

                    b.HasIndex("roomid");

                    b.ToTable("usersrooms", (string)null);
                });

            modelBuilder.Entity("AA2_CS.Model.BodyMetric", b =>
                {
                    b.HasOne("AA2_CS.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AA2_CS.Model.NotificationPreference", b =>
                {
                    b.HasOne("AA2_CS.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AA2_CS.Model.Purchase", b =>
                {
                    b.HasOne("AA2_CS.Model.Item", "Item")
                        .WithMany()
                        .HasForeignKey("itemid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AA2_CS.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AA2_CS.Model.Subscription", b =>
                {
                    b.HasOne("AA2_CS.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AA2_CS.Model.TaskExercise", b =>
                {
                    b.HasOne("AA2_CS.Model.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AA2_CS.Model.Task", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("AA2_CS.Model.User", b =>
                {
                    b.HasOne("AA2_CS.Model.Item", "EquippedEnduranceItem")
                        .WithMany()
                        .HasForeignKey("equippedEnduranceId");

                    b.HasOne("AA2_CS.Model.Item", "EquippedStrengthItem")
                        .WithMany()
                        .HasForeignKey("equippedStrengthId");

                    b.Navigation("EquippedEnduranceItem");

                    b.Navigation("EquippedStrengthItem");
                });

            modelBuilder.Entity("AA2_CS.Model.UserAchievement", b =>
                {
                    b.HasOne("AA2_CS.Model.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AA2_CS.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AA2_CS.Model.UserRoom", b =>
                {
                    b.HasOne("AA2_CS.Model.Room", "Room")
                        .WithMany()
                        .HasForeignKey("roomid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AA2_CS.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
